import "./globals.css";
import { Zeyada, Inter, Space_Grotesk } from "next/font/google";

const zeyada = Zeyada({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-zeyada",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${zeyada.variable} ${inter.variable} ${space.variable} scroll-smooth`}
    >
      <body className="bg-hero-pattern">{children}</body>
    </html>
  );
}
